name: leacc_factory
version: 1.0.0+1
publish_to: none
description: A new Flutter project of LeAcc Factory.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  path_provider: ^2.0.11
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  http: ^0.13.4
  cookie_jar: 3.0.1
  async_button_builder: ^2.3.0+1
  flutter_initicon: ^2.0.0
  flutter_form_builder: ^7.4.0
  form_builder_validators: ^8.2.0
  lazy_load_scrollview: 1.3.0
  badges: ^2.0.3
  get_storage: ^2.0.3
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  awesome_dialog: ^3.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

